const AnimeData = [
  {
    id: 1,
    name: "naruto",
    img: "/img/Naruto.jfif",
    bg: "/bg/narutobg.jpg",
    bgImg: "",
    seasons: "12",
    noOfEp: "700",
    type: "Tv",
    time: "23",
    date: "",
    genre: "Action",
    status: "finished",
    description: "",
  },
  {
    id: 2,
    name: "Black clover: sword of the wizard king",
    img: "/img/blackclover.jpg",
    bg: "/bg/blackcliverbg.jpe",
    bgImg: "",
    seasons: "",
    noOfEp: "",
    type: "Movie",
    genre: "Action",
    time: "1hr 55min",
    date: "june 20, 2023",
    status: "finished",
    description: "",
  },
  {
    id: 3,
    name: "That time i Got Reincarnated as a Slime",
    namest: "That time i...",
    title: "",
    img: "/img/RencarnatedSlime.jfif",
    bg: "/bg/slimebg.jpg",
    bgImg: "",
    seasons: "2",
    noOfEp: "48",
    type: "Tv",
    genre: "Fantasy",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 4,
    name: "Jujutsu Kaisen",
    img: "/img/jujutsu_kaisen.jpg",
    bg: "",
    seasons: "5",
    noOfEp: "300",
    type: "Tv",
    genre: "Action",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 5,
    name: "Kaguya sama: Love is war",
    img: "/img/LoveisWar.jfif",
    bg: "/bg/loveiswarbg.jpg",
    bgImg: "",
    seasons: "3",
    noOfEp: "36",
    type: "Tv",
    genre: "Romace",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 6,
    name: "Horimiya",
    img: "/img/Horimiya.jfif",
    bg: "/bg/horimiyabg.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    genre: "Romace",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 7,
    name: "The Devil is a part timer",
    img: "/img/parttimer.jpg",
    bg: "/bg/devilbg.jpg",
    bgImg: "",
    seasons: "7",
    noOfEp: "400",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
    genre: "Romace",
  },
  {
    id: 8,
    name: "Haikyu",
    img: "/img/haikyu.jpg",
    bg: "/bg/haikyuubg.jpg",
    bgImg: "",
    seasons: "4",
    noOfEp: "72",
    type: "Tv",
    genre: "Sports",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 9,
    name: "Spy x Family",
    img: "/img/spyFamily.jpg",
    bg: "/bg/spyxbg.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "24",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 10,
    name: "Over Lord",
    img: "/img/overlord.jpg",
    bg: "/bg/overlordbg.jpg",
    bgImg: "",
    seasons: "4",
    noOfEp: "72",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 11,
    title: "Saga of Tanya the evil",
    img: "/img/saga.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "24",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 12,
    title: "Science fell in love",
    img: "/img/fellinlove.jpg",
    bgImg: "",
    seasons: "2",
    noOfEp: "48",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 13,
    title: "More than a married couple",
    img: "/img/married.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 14,
    title: "Loving Yamada-kun at lv999",
    img: "/img/lv999.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    time: "23",
    date: "may 20, 2023",
    status: "finished",
    description: "",
  },
  {
    id: 15,
    title: "Demon slayer",
    img: "/img/kimetsu.jpg",
    bgImg: "",
    seasons: "3",
    noOfEp: "36",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 16,
    title: "86 Eighty six",
    img: "/img/8six.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "24",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 17,
    title: "Chain Saw man",
    img: "/img/chain.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    time: "23",
    date: "may 20, 2022",
    status: "finished",
    description: "",
  },
  {
    id: 18,
    title: "Class ROOM OF THE ELITE",
    img: "/img/classe.jpg",
    bgImg: "",
    seasons: "2",
    noOfEp: "24",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 19,
    title: "The dangers in my heart",
    img: "/img/dangers.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    time: "23",
    date: "may 20, 2023",
    status: "finished",
    description: "",
  },
  {
    id: 20,
    title: "Eminence in the shadow",
    img: "/img/emShadow.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "20",
    type: "Tv",
    time: "23",
    date: "may 20, 2022",
    status: "finished",
    description: "",
  },
  {
    id: 21,
    title: "Hells Paradise",
    img: "/img/hellsp.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    time: "23",
    date: "may 20, 2023",
    status: "finished",
    description: "",
  },
  {
    id: 22,
    title: "One Piece",
    img: "/img/one-piece.jpg",
    bgImg: "",
    seasons: "??",
    noOfEp: "1065",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "Airing",
    description: "",
  },
  {
    id: 23,
    title: "So im a spider so what",
    img: "/img/spidersowhat.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
  {
    id: 24,
    title: "Redo of the healer",
    img: "/img/Redoofhealer.jpg",
    bgImg: "",
    seasons: "1",
    noOfEp: "12",
    type: "Tv",
    time: "23",
    date: "may 20, 2020",
    status: "finished",
    description: "",
  },
];
export default AnimeData;
